# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54037600ab530804e34b14b901642d2760f7575992fc823a76988c583864b196c5c561ea336581cbe0a3d6d9036a218781907b454b40e95df3be405084b9c0cd

test:
  secret_key_base: f18b381bd4f8a2c70a7675518294e9243cd4a4d60b6f81e7c606e9bbc16799bb9e416e18378d752ca10522d72262b0a0e4e34d15e0509b73a77170e409cb0a29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
